In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
1
(5,)
5
int64


In [2]:
import numpy as np
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [3]:
import numpy as np
np.arange(5,500,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130,
       135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195,
       200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260,
       265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325,
       330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385, 390,
       395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450, 455,
       460, 465, 470, 475, 480, 485, 490, 495])

In [5]:
np.arange(500,50,-5)

array([500, 495, 490, 485, 480, 475, 470, 465, 460, 455, 450, 445, 440,
       435, 430, 425, 420, 415, 410, 405, 400, 395, 390, 385, 380, 375,
       370, 365, 360, 355, 350, 345, 340, 335, 330, 325, 320, 315, 310,
       305, 300, 295, 290, 285, 280, 275, 270, 265, 260, 255, 250, 245,
       240, 235, 230, 225, 220, 215, 210, 205, 200, 195, 190, 185, 180,
       175, 170, 165, 160, 155, 150, 145, 140, 135, 130, 125, 120, 115,
       110, 105, 100,  95,  90,  85,  80,  75,  70,  65,  60,  55])

In [8]:
import numpy as np
np.linspace(0,1,5) #5-1=4 1/4=0.25  

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.zeros((2,3)) #array with all zero with dimension 2 row 3 col

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(3) #identity matrix with all one 3*3 dimension

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])