In [ ]:
#operations
#indexing

In [7]:

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[1,2])
print(a[0,2])


6
3


In [9]:
#slicing- a part
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[1,:])
print(a[0,:])

[4 5 6]
[1 2 3]


In [17]:
#array operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(a**b)
print(b**3)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[  1  32 729]
[ 64 125 216]


In [19]:
a=np.array([1,2,3])
print(a>1)
print(a==1)

[False  True  True]
[ True False False]


In [21]:
np.sqrt(([1,4,9]))

array([1., 2., 3.])

In [25]:
import numpy as np
np.sin([0,np.pi/2])

array([0., 1.])

In [26]:
a=np.array([[1],[2],[3]])
b=np.array([4,5,6])
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
